from enum import Enum

class LicitacionStatus(str, Enum):
    PENDIENTE = "PENDIENTE"
    PROCESANDO_DOCUMENTOS = "PROCESANDO_DOCUMENTOS"
    DOCUMENTOS_PROCESADOS = "DOCUMENTOS_PROCESADOS"
    EXTRACCION_SEMANTICA_EN_PROCESO = "EXTRACCION_SEMANTICA_EN_PROCESO"
    EXTRACCION_SEMANTICA_COMPLETADA = "EXTRACCION_SEMANTICA_COMPLETADA"
    ERROR = "ERROR"

class FileStatus(str, Enum):
    PENDIENTE = "PENDIENTE"
    PROCESANDO = "PROCESANDO"
    PROCESADO = "PROCESADO"
    ERROR = "ERROR"
